### ISSUE TITLE
minor suggestion for eqb function in zurcher.m file

### ISSUE THREAD

**Issue by choiHenry** [bschjerning/dp_ucph#1]
Hi I am a ph.d student in Seoul, Korea(South). I am currently reviewing Rust(1987) paper.
I really appreciate this repo and the associated lectures on your Youtube channel.
Thank you very much.

Reviewing the code I found a minor typo in zurcher.m file.
Below is the ergodic function part of zurcher.m file.
The 5th line of the ergodic function checks whether the matrix **p** is symmetric.
Thus the code should check whether the first and second dimensions of **p** are the same.
Then the fifth line would be **if n ~= size(p, 2)**.
This is just a minor issue i think.

Regards,
Henry.

```matlab
    function ed=ergodic(p);
      % ergodic.m: finds the invariant distribution for 
      % an NxN Markov transition probability
      n=size(p,1);
      if n ~= size(p,1);
        fprint('Error: p must be a square matrix\n');
        ed=NaN;
      else
        ap=eye(n)-p';
        ap=[[ap; ones(1,n)], ones(n+1,1)];
        if (rank(ap) < n+1);
          fprintf('Error: transition matrix p is not ergodic\n');
          ed=NaN;
        else
          ed=[ones(n,1); 2];
          ed=ap\ed;
          ed(end)=[];
          ed=reshape(ed,1,[]); %row vector
        end;
      end
    end % end of ergodic
```

**Comment by bschjerning** [comment]
Dear Henry

Thanks for this. I will correct the bug. Let me know if you find any more bugs, or if you would like to meet for a quick Zoom chat about your research some time.

Bertel

Bertel Schjerning
Professor, PhD
Department of Economics
University of Copenhagen
Email: ***@***.******@***.***>
Web: www.bschjerning.com<http://www.bschjerning.com/>
Phone: (+45) 28352132





On 19 Mar 2022, at 15.19, Henry ***@***.******@***.***>> wrote:


You don't often get email from ***@***.******@***.***>. Learn why this is important<http://aka.ms/LearnAboutSenderIdentification>



Hi I am a ph.d student in Seoul, Korea(South). I am currently reviewing Rust(1987) paper.
I really appreciate this repo and the associated lectures on your Youtube channel.
Thank you very much.

Reviewing the code I found a minor typo in zurcher.m file.
Below is the ergodic function part of zurcher.m file.
The 5th line of the ergodic function checks whether the matrix p is symmetric.
Thus the code should check whether the first and second dimensions of p are the same.
Then the fifth line would be if n ~= size(p, 2).
This is just a minor issue i think.

Regards,
Henry.

    function ed=ergodic(p);
      % ergodic.m: finds the invariant distribution for
      % an NxN Markov transition probability
      n=size(p,1);
      if n ~= size(p,1);
        fprint('Error: p must be a square matrix\n');
        ed=NaN;
      else
        ap=eye(n)-p';
        ap=[[ap; ones(1,n)], ones(n+1,1)];
        if (rank(ap) < n+1);
          fprintf('Error: transition matrix p is not ergodic\n');
          ed=NaN;
        else
          ed=[ones(n,1); 2];
          ed=ap\ed;
          ed(end)=[];
          ed=reshape(ed,1,[]); %row vector
        end;
      end
    end % end of ergodic

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbschjerning%2Fdp_ucph%2Fissues%2F1&data=04%7C01%7Cbertel.schjerning%40econ.ku.dk%7C2473096d41584414b2d708da09b37e5f%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637832963769008752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GcqMP61vlUa9u53cw0TOpW7f4vfZDWbkENTi9kLHKOw%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGBHRV6MW5OBYHHVMT7N4R3VAXO7LANCNFSM5RECTEHQ&data=04%7C01%7Cbertel.schjerning%40econ.ku.dk%7C2473096d41584414b2d708da09b37e5f%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637832963769008752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Cx58C6Gt%2Bnfov9aDbVbWbGyCIZjneusWAumNPRCH%2FjY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbertel.schjerning%40econ.ku.dk%7C2473096d41584414b2d708da09b37e5f%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637832963769008752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NUFH6dSCX2ZoCfcE0F9KYvN5v2x9EqfSg9uw5dQSGGA%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbertel.schjerning%40econ.ku.dk%7C2473096d41584414b2d708da09b37e5f%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637832963769008752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BNZBvxxpa8S9rrFnmtMcgnY4Sd1IiJU4XHicJg7sVBo%3D&reserved=0>.

**Comment by choiHenry** [comment]
Thank you for your response:) I really hope to meet you in zoom sometime when my research is developed sufficiently.


With many thanks,
Henry.
